import { clsx } from "clsx";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { twMerge } from "tailwind-merge";

export const metadata: Metadata = {
  title: "Rohit Kushwaha",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();

  const fontClass = clsx({
    "font-english": locale === "en",
    "font-korean": locale === "kr",
    "font-hindi": locale === "hi",
  });

  console.log(fontClass);

  return (
    <html lang={locale}>
      <body
        className={twMerge(fontClass, "bg-gray-900 text-white min-h-screen")}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
